### ISSUE TITLE
无法批量发送卡片消息

### ISSUE THREAD

**Issue by gaoliang** [larksuite/appframework-java#10]
```java
java.lang.UnsupportedOperationException: card message not contain content field
	at com.larksuite.appframework.sdk.client.message.CardMessage.getContentKey(CardMessage.java:40)
	at com.larksuite.appframework.sdk.client.LarkClient.lambda$doBatchSendChatMessage$9(LarkClient.java:357)
	at com.larksuite.appframework.sdk.client.LarkClient.retryIfTenantAccessTokenInvalid(LarkClient.java:419)
	at com.larksuite.appframework.sdk.client.LarkClient.doBatchSendChatMessage(LarkClient.java:351)
	at com.larksuite.appframework.sdk.client.LarkClient.batchSendChatMessage(LarkClient.java:83)
```

**Comment by xionghan00** [comment]
1.0.7    fixed,  card message 协议有些特殊， batch send 没有做适配
